---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-centos-7
    image: centos:7
  - name: ansible-centos-6
    image: centos:6
  - name: ansible-ubuntu-1604
    image: ubuntu:16.04
  - name: ansible-ubuntu-1404
    image: ubuntu:14.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
